---
- name: Cisco - Get running configuration
  ios_config:
    backup: yes
    backup_options:
      filename: "{{inventory_hostname}}.cfg"
      dir_path: "{{git_network_backup_configs}}/"
  register: saved_configuration
  when: ansible_network_os == "ios"

- name: Git - Is it up-to-date?
  delegate_to: localhost
  run_once: true
  shell: "git status ."
  args:
    chdir: "{{git_network_backup_configs}}"
  register: git
  when: saved_configuration is defined

- name: Git - Add config file for devices
  delegate_to: localhost
  run_once: true
  shell: "git add *"
  args:
    chdir: "{{git_network_backup_configs}}"
  register: gitadd
  when: git is defined

- debug:
    msg: "{{ gitadd }}"

- name: Git - Commit config file for devices
  delegate_to: localhost
  run_once: true
  shell: 'git commit * -m "Ansible Automatic Backup - {{cur_date_time}}"' 
  args:
    chdir: "{{git_network_backup_configs}}"
  register: gitcommit
  when: gitadd.changed == True

    #- name: Git - Push config file for devices
    #  delegate_to: localhost
    #  shell: git push 
    #  args:
    #    chdir: "{{git_network_backup_configs}}"
    #  register: gitpush
    #  when: inventory_hostname in git.stdout
    #
