---
- name: Cisco - Get running configuration
  ios_config:
    backup: yes
    backup_options:
      filename: "{{inventory_hostname}}.cfg"
      dir_path: "{{git_network_backup_configs}}/"
  register: config
  when: ansible_network_os == "ios"

- name: Git - Satatus
  shell: "git status {{git_network_backup_configs}}/*"
  register: gitstatus
  when: config is defined
  run_once: true
  delegate_to: localhost
  changed_when: False

- name: Git - Add config files 
  shell: "git add {{git_network_backup_configs}}/*"
  register: gitadd
  when: '"Untracked" in gitstatus.stdout or "modified" in gitstatus.stdout'
  run_once: true
  delegate_to: localhost

- name: Git - Commit changed config file 
  shell: 'git commit {{git_network_backup_configs}}/* -m "Ansible Automatic Backup - {{cur_date_time}}"' 
  register: gitcommit
  when: gitadd.changed
  run_once: true
  delegate_to: localhost

- name: Git - Push config files
  shell: "git push" 
  register: gitpush
  when: gitcommit.changed
  run_once: true
  delegate_to: localhost

- name: Git - Watch config diff on github
  debug:
    msg: "https://github.com/0lesen/H6-Projekt/tree/master/ansible/networking/backup_configs"
  when: gitpush.changed
  run_once: true
  delegate_to: localhost
