---    
- name: "Run local python script: create_new_vlan_documentation.py"
  shell: '''create_new_vlan_documentation.py -name {{ new_vlan_name }} -id {{ new_vlan_id }} -subnet {{ new_vlan_subnet }} -prefix {{ new_vlan_prefix }}'''
  args:
    chdir: "roles/test-add-new-vlan-to-netbox/files"
    executable: /usr/bin/python3
  delegate_to: localhost
