### Set timzone 
- name: set timezone to Europe/Copenhagen
  become: true
  timezone:
    name: Europe/Copenhagen
  notify:
    - update timezone

### create users
- name: Make sure wheel group exsists
  become: true
  group:
    name: wheel
    state: present

- name: Allow wheel users to have pswd'less sudo
  become: true
  lineinfile:
    dest: /etc/sudoers
    state: present
    regexp: '^%wheel'
    line: '%wheel ALL=(ALL) NOPASSWD: ALL'

- name: Add user Test bruger
  become: true
  user:
    name: test
    comment: Test bruger til netupnu
    shell: /bin/bash
    groups: wheel
    append: yes
    password: $6$LMvYHxLeeaor1PpP$dzmEMmXzZs63xNX.pRYnqGOEzqNI/6PxrHMkGpzPfFeQT14JqPHpnLL.xzN4Pa9LtUzyT2yLCVttZ4OsBZQxu1
    state: present

- name: Add Test user pub key
  become: true
  authorized_key:
    user: test
    state: present
    key: sk-ssh-ed25519@openssh.com AAAAGnNrLXNzaC1lZDI1NTE5QG9wZW5zc2guY29tAAAAIDn4WBaU0zKOXlQgoZd4VSUCxi42Sru+ad0OXtzeLvOAAAAABHNzaDo= TEST-29-11-2021-KEY2


### SNMP install
- name: Install SNMPD
  apt: pkg=snmpd state=present

- name: Download LibreNMS distro file from github to be able to determine OS with snmp 
  get_url:
    url: https://raw.githubusercontent.com/librenms/librenms-agent/master/snmp/distro
    dest: /usr/bin/distro
    mode: +x 

- name: Create /etc/snmp/snmpd.conf from template with community and location as variables
  template:                                                                     
    src: ./roles/netupnu-default/files/snmpd.conf                            
    dest: /etc/snmp/
  when: 'custom_fields.snmp == true'
  notify: restart snmpd

### rsyslog client install
- name: Install Rsyslog
  apt: pkg=rsyslog state=present
  when: "'nms' not in inventory_hostname"

- name: Add line to rsyslog.conf file
  become: true
  lineinfile:
    dest: /etc/rsyslog.conf
    state: present
    line: 'auth,authpriv.* @{{nms_ip}}'
  notify: restart rsyslog
  when: "'nms' not in inventory_hostname" 

### Fix multipath error on ubuntu hosts
- name: Fix multipath
  copy:                                                                     
    src: ./roles/netupnu-default/files/multipath.conf                            
    dest: /etc/multipath.conf
  notify: restart multipath
