### Set timzone 
- name: set timezone to Europe/Copenhagen
  timezone:
    name: Europe/Copenhagen
    become: yes
    become_method: sudo
    notify:
      - update timezone



### create users

- name: Make sure wheel group exsists
  become: true
  group:
    name: wheel
    state: present

- name: Allow wheel users to have pswd'less sudo
  become: true
  lineinfile:
    dest: /etc/sudoers
    state: present
    regexp: '^%wheel'
    line: '%wheel ALL=(ALL) NOPASSWD: ALL'
      

- name: Add user Mikkel Bank Olesen
  become: true
  user:
    name: mbo
    comment: Automate borring stuff
    shell: /bin/bash
    groups: wheel
    append: yes
    password: $6$f9jCGHLchWH5HXVe$BAsLGigYnmxlIMggxWYTsHY4ufhS0OqedW7LtU3zxJcj/MntfWQeYjhBshXXQqG/cxFbzFXlYWhZo2aE.5gkc/
    state: present

- name: Add Mikkel Bank Olesen pub key
  become: true
  authorized_key:
    user: mbo
    key: "sk-ssh-ed25519@openssh.com AAAAGnNrLXNzaC1lZDI1NTE5QG9wZW5zc2guY29tAAAAIPhmh2MM+o8YAzOoH2Yg00oj+sfS/uc0QE8FqT7y9xm6AAAABHNzaDo="
    state: present

- name: Add user Mikkel Leth
  become: true
  user:
    name: mkl
    comment: SQL master2000
    shell: /bin/bash
    groups: wheel
    append: yes
    password: $5$QNFEryGUvC9pMCB$KVaPqaNKRErP71Y6B2c2juEnrMUhSda5YouU2FOr390
    state: present


### SNMP install

- name: Install SNMPD
  apt: pkg=snmpd state=present

- name: Download LibreNMS distro file from github to be able to determine OS with snmp 
  get_url:
    url: https://raw.githubusercontent.com/librenms/librenms-agent/master/snmp/distro
    dest: /usr/bin/distro
    mode: +x 

- name: Create /etc/snmp/snmpd.conf from template with community and location as variables
  template:                                                                     
    src: ./roles/snmp/files/snmpd.conf                            
    dest: /etc/snmp/
  notify: restart snmpd


### APPLICATIONS START ###
# BIND DNS STATS
- name: Download LibreNMS BIND script file from github
  become: true
  get_url:
    url: https://github.com/librenms/librenms-agent/raw/master/snmp/bind 
    dest: /etc/snmp/bind 
    mode: +x
  when: 'apps is defined and "bind" in apps'

- name: Add BIND extend to snmpd.conf if host is a BIND server 
  lineinfile:
    path: /etc/snmp/snmpd.conf
    line: "extend bind /etc/snmp/bind"
  when: 'apps is defined and "bind" in apps'
  notify: restart snmpd
  become: true 

# DHCP STATS
- name: Download LibreNMS DHCP-SERVER file from github to be able to gather DHCP info with snmp 
  get_url:
    url: https://github.com/librenms/librenms-agent/raw/master/snmp/dhcp.py
    dest: /etc/snmp/dhcp.py
    mode: +x 
  notify: restart snmpd
  when: '"DHCP" in snmp.extend'

- name: Create /etc/snmp/dhcp.json file
  copy:                                                                     
    src: roles/snmp/files/dhcp.json                            
    dest: /etc/snmp/dhcp.json
  notify: restart snmpd
  when: '"DHCP" in snmp.extend'
