---    
- name: Configure IP adress on vlan interfaces
  ios_config:
    lines: 
      - "ip address {{ item.1.address | ipaddr('host/prefix') | ipaddr('address') }} {{ item.1.address | ipaddr('host/prefix') |ipaddr('netmask') }}"
    parents: "interface {{ item.0.name }}"
  with_nested:	
    - "{{ interfaces.json.results }}"	
    - "{{ ip_addresses.json.results }}"	
  loop_control:
    label: "Interface: {{ item.0.name }} - IP address: {{ item.1.address }}"
  when: 'item.0.enabled and item.0.type.value == "virtual" and item.0.id == item.1.assigned_object_id'
 
- name: Configure default gateway
  ios_config:
    lines: 
      - "ip default-gateway {% set netnetnet = item.1.address | ipaddr('network') %}{% set netnet = netnetnet + '/' ~ item.1.address | ipaddr('prefix') %}{{ netnet | ipaddr('net') | ipaddr('1') | regex_replace('[/][^/]*$', '') }}"
  with_nested:	
    - "{{ interfaces.json.results }}"	
    - "{{ ip_addresses.json.results }}"	
  loop_control:
    label: "Interface: {{ item.0.name }} - IP address: {{ item.1.address }}"
  when: 'item.0.enabled and item.0.type.value == "virtual" and item.0.id == item.1.assigned_object_id'
