---
- name: restart snmpd 
  service: name=snmpd state=restarted
  become: true

- name: restart rsyslog 
  service: name=rsyslog state=restarted
  become: true

- name: restart multipath 
  service: name=multipathd state=restarted
  become: true

- name: update timezone
  command: dpkg-reconfigure --frontend noninteractive tzdata
  become: true
