---
- name: restart snmpd 
  service: name=snmpd state=restarted
  become: true

- name: restart timezone 
  service: name=snmpd state=restarted
  become: true

- name: update timezone
  command: dpkg-reconfigure --frontend noninteractive tzdata
  become: true
