---    
- name: OSPF Process
  ios_config:
    lines:
      - "router ospf {{ospf.process_id}}"
  when: ospf.process_id is defined

- name: OSPF Process - Router ID
  ios_config:
    lines: 
      - "router-id {{ ospf.router_id }}"
    parents: "router ospf {{ospf.process_id}}"
  when: 
    - ospf.process_id is defined
    - ospf.router_id is defined

- name: OSPF Default passive interface
  ios_config:
    lines: 
      - "passive-interface default"
    parents: "router ospf {{ospf.process_id}}"
  when: 
    - ospf.passive_default 

- name: OSPF Interfaces
  ios_config:
    lines:
      - "ip ospf {{ ospf.process_id }} area {{ item.area }}"
    parents: "interface {{ item.name }}"
  with_items: "{{ ospf.interfaces }}"
  when:
    - ospf.process_id is defined
    - item is defined


- name: OSPF Interfaces - No passive interface
  ios_config:
    lines:
      - "no passive-interface {{ item.name }}"
    parents: "router ospf {{ ospf.process_id }}"
  when: 
    - ospf.process_id is defined
    - item is defined
    - not item.passive
  loop: "{{ ospf.interfaces }}"

- name: OSPF Interfaces - Authentication
  ios_config:
    lines:
      - "ip ospf authentication message-digest"
      - "ip ospf message-digest-key {{ ospf.auth_key_id }} {{ ospf.auth_encryption }} {{ ospf.auth_secret }}"
    parents: "interface {{ item.name }}"
  when: 
    - ospf.auth_key_id is defined
    - ospf.auth_encryption is defined
    - ospf.auth_secret is defined
    - item.auth 
  loop: "{{ ospf.interfaces }}"
