---    
- name: N0 Shutdown enabled interfaces
  ios_config:
    lines:
      - "no shutdown"
    parents: "interface {{ item.name }}"
  with_items: "{{ interfaces.json.results }}"
  when: 'item.enabled'
  loop_control:
    label: "Interface {{ item.name }}"

- name: Configure encapsulation on interfaces
  ios_config:
    lines:
      - "encapsulation dot1Q {{ item.name | regex_replace('^([^.]*).', '') }}"
    parents: "interface {{ item.name }}"
  with_items: "{{ interfaces.json.results }}"
  loop_control:
    label: "Interface {{ item.name }}"
  when: 'item.enabled and item.type.value == "virtual"'


- name: Configure IP adress on sub interfaces
  ios_config:
    lines: 
      - "ip address {{ item.1.address | ipaddr('host/prefix') | ipaddr('address') }} {{ item.1.address | ipaddr('host/prefix') |ipaddr('netmask') }}"
    parents: "interface {{ item.0.name }}"
  with_nested:	
    - "{{ interfaces.json.results }}"	
    - "{{ ip_addresses.json.results }}"	
  loop_control:
    label: "Interface {{ item.0.name }} - IP address {{ item.1.address }} "
  when: 'item.0.enabled and item.0.type.value == "virtual" and item.0.id == item.1.assigned_object_id'
 

- name: Add ip helper to sub interfaces
  ios_config:
    lines:
      - "ip helper-address 10.0.20.4"
    parents: "interface {{ item.name }}"
  with_items: "{{ interfaces.json.results }}"
  loop_control:
    label: "Interface {{ item.name }}"
  when: 'item.enabled and item.type.value == "virtual"'

- name: "Add sub interfaces to ospf process id 1 and area 0"
  ios_config:
    lines:
      - "ip ospf 1 area 0"
    parents: "interface {{ item.name }}"
  with_items: "{{ interfaces.json.results }}"
  loop_control:
    label: "Interface {{ item.name }}"
  when: 'item.enabled and item.type.value == "virtual"'
