#!/usr/bin/python3
import crypt,random,string,getpass
name = input("Full name: ")
user = input("Username: ")
comment = input("Comment: ")
pub_key = input("Public key: ")
password = crypt.crypt(getpass.getpass('clear-text password: '), crypt.mksalt(crypt.METHOD_SHA512))

res = """
- name: Add user {0}
  become: true
  user:
    name: {1}
    comment: {2}
    shell: /bin/bash
    group: wheel
    append: yes
    password: {3}
    state: present

- name: Add {0} pub key
  become: true
  authorized_key:
    user: {1}
    state: present
    key: {4}
""".format(name, user, comment, password, pub_key)
print(res)
