---    
- name: Create ACCESS interfaces
  ios_config:
    lines:
      - "switchport mode access"
      - "switchport access vlan {{ item.untagged_vlan.vid }}"
      - "spanning-tree portfast"
      - "spanning-tree bpduguard enable"
    parents: "interface {{ item.name }}"
  with_items: "{{ interfaces.json.results }}"
  loop_control:
    label: "Interface: {{ item.name }}"
  when: 'item.mode and item.mode.value == "access" and item.untagged_vlan != "None"'

- name: Configure vlans on TRUNK interfaces
  ios_config:
    lines:
      - "switchport mode trunk"
      - "switchport trunk allowed vlan add {{ item.1.vid }}"
    parents: "interface {{ item.0.name }}"
  with_subelements:	
    - "{{ interfaces.json.results }}"	
    - "tagged_vlans"	
    - skip_missing: True
  loop_control:
    label: "Interface: {{ item.0.name }} - VLAN ID: {{ item.1.vid }}"
  when: 'item.0.mode and item.0.mode.value == "tagged"'
