---
- hosts: 
    - device_roles_dc-switch
  gather_facts: no
  vars:
     site_name: "dc01" 

  roles:
    - cisco-git-backup
    - get-netbox-data
    - cisco-vlans
    - cisco-l2-interfaces
    - cisco-git-backup
