---
- hosts: localhost

- name: Creating new vlan in netbox
  import_playbook: add_new_vlan_to_netbox.yml 

- name: Creating vlan on vmware cluster
  import_playbook: add_new_vlan_to_cluster.yml 

- name: Create vlan on cluster switches
  import_playbook: cisco_add_vlans.yml

- name: Create new vlan on firewall 
  import_playbook: add_new_vlan_to_fortigate.yml 
