---
- hosts: 
    - device_roles_site_switch
  gather_facts: no

  roles:
    - get-netbox-data

  tasks:
    - name: Generating configuration template with data from Netbox
      template:
        src: ./sites-basic-config/base_sw_config_tempalte.j2
        dest: "./sites-basic-config/{{ inventory_hostname }}.cfg"
      delegate_to: localhost
