---
- hosts:
    - "sites_{{ new_site_name }}_s{{ new_site_id}}" 

  vars_files:
    - "./vars/new_site.yml"

  gather_facts: no
  vars:
      site_name: "{{ new_site_name }}_s{{ new_site_id }}" 

  roles:
    - cisco-git-backup
    - cisco-hostname
    - cisco-timezone
    - test-get-netbox-data
    - test-cisco-vlans
    - test-cisco-l2-interfaces
    - test-cisco-sw-l3-interfaces
