### Denne playbook har til formål at konfigurer core routeren
---
- hosts:
    - device_roles_core_router 
  gather_facts: true

  roles:
    - get-netbox-data
    - cisco-git-backup
    - cisco-l3-interfaces
    - cisco-git-backup

  tasks: 
    - name: Print message to user 
      debug:
        msg: "Please validate SSH connection to new site switche before running next step" 
      run_once: true
