---    
### Denne playbook har til formål at opret dokumentation for nyt site
### playbooken køre rollen "add-new-site-to-netbox" som kører et python3 script lokalt, hvor den opretter nyt site i Netbox baseret på variable værdierne i under ./vars/new_site.yml - ændre disse inden playbooken køres!

- hosts: localhost
  vars_files:
    - ./vars/new_site.yml

  roles:
    - add-new-site-to-netbox
