---
- hosts: 
  #    - platforms_ios
    - sites_aar-s01
  gather_facts: no
  vars:
     site_name: "aar-s01" 

  roles:
    - test-get-netbox-data
    - test-cisco-vlans
    - test-cisco-l2-interfaces
      #    - cisco-interfaces_lag
      #    - cisco-storm-control
