---
- hosts: 
    - platforms_ios
  gather_facts: no

  roles:
    - test-get-netbox-data
    - test-cisco-vlans
    - test-cisco-l2-interfaces
      #    - cisco-interfaces_lag
      #    - cisco-storm-control
