---
- hosts: 
    - device_roles_dc-switch
  gather_facts: no
  vars:
     site_name: "dc01" 

  roles:
    - cisco-git-backup
    - test-get-netbox-data
    - test-cisco-vlans
    - test-cisco-l2-interfaces
    - cisco-git-backup
