---
- hosts: 
  #    - platforms_ios
    - sites_aar-s01
  gather_facts: no
  vars:
     site_name: "aar-s01" 

  roles:
    - cisco-git-backup
    - cisco-hostname
    - cisco-timezone
    - test-get-netbox-data
    - test-cisco-vlans
    - test-cisco-l2-interfaces
    - test-cisco-sw-l3-interfaces
