---
- hosts:
    #- "sites_{{ new_site_name }}_s{{ new_site_id}}" 
    - "sites_aar_s01" 

  vars_files:
    - "./vars/new_site.yml"

  gather_facts: no
  vars:
      site_name: "{{ new_site_name }}_s{{ new_site_id }}" 

  roles:
    - cisco-snmp

  tasks: 
    - name: Print message to user 
      debug:
        msg: '{{ hostvars[inventory_hostname].sites }}'
