---    
- name: Configure VLAN ID
  ios_config:
    lines:
      - "vlan {{ item.id }}"
  with_items: "{{ vlans }}"
  when: 'vlans is defined and vlans and item.state == "Active"'

- name: Configure VLAN Name
  ios_config:
    lines:
      - "name {{ item.name }}"
    parents: "vlan {{ item.id}}"
  with_items: "{{ vlans }}"
  when: 'vlans is defined and vlans and item.state == "Active"'

- name: Delete VLAN ID
  ios_config:
    lines:
      - "no vlan {{ item.id }}"
  with_items: "{{ vlans }}"
  when: 'vlans is defined and vlans and item.state == "Deprecated"'
 
