---    
- name: Configure VLAN ID
  ios_config:
    lines:
      - "vlan {{ item.vid }}"
  with_items: "{{ vlans.json.results }}"
  loop_control:
    label: "Vlan ID: {{ item.vid }}"
  when: 'vlans is defined and vlans and item.status.value == "active"'

- name: Configure VLAN Name
  ios_config:
    lines:
      - "name {{ item.name }}"
    parents: "vlan {{ item.vid}}"
  with_items: "{{ vlans.json.results }}"
  loop_control:
    label: "Vlan name: {{ item.name }} - Vlan ID: {{ item.vid }}"
  when: 'vlans is defined and vlans and item.status.value == "active"'
