---
plugin: netbox.netbox.nb_inventory
api_endpoint: https://netbox01.netupnu.dk
token: bbbf9087d591f7651da4b8f2ce0d13ad071927bc
validate_certs: False
config_context: False
group_by:
  - device_roles
  - sites
  - platforms

#query_filters:
#  - tag: 'site'

# Get devices with primary ip
device_query_filters:
  - has_primary_ip: 'true'

# Insert informations as Ansible-facts on hosts
compose:
  ansible_network_os: platform.slug
  custom_fields: custom_fields
