---    
- name: Create vlan interfaces.
  fortios_system_interface:
    vdom:  "root"
    state: "present"
    access_token: "{{ api_token }}"
    system_interface:
      vdom:  "root"
      name: "{{ item.name }}"
      mode: "static"
      allowaccess: "ping"
      interface: "DATACENTER"
      ip: "{{ network }}"
      speed: "auto"
      status: "up"
      type: "vlan"
      vlan_protocol: "8021q"
      vlanid: "{{ item.vid }}"
  with_items: "{{ vlans.json.results }}"
  when: 'vlans is defined and vlans and item.status.value == "active"'






  #
  #- name: Configure VLAN ID
  #  ios_config:
  #    lines:
  #      - "vlan {{ item.vid }}"
  #  with_items: "{{ vlans.json.results }}"
  #  when: 'vlans is defined and vlans and item.status.value == "active"'
  #
  #- name: Configure VLAN Name
  #  ios_config:
  #    lines:
  #      - "name {{ item.name }}"
  #    parents: "vlan {{ item.vid}}"
  #  with_items: "{{ vlans.json.results }}"
  #  when: 'vlans is defined and vlans and item.status.value == "active"'
  #
  #- name: Delete VLAN ID
  #  ios_config:
  #    lines:
  #      - "no vlan {{ item.vid }}"
  #  with_items: "{{ vlans.json.results }}"
  #  when: 'vlans is defined and vlans and item.status.value == "deprecated"'
