---    
- name: Create vlan interfaces.
  fortios_system_interface:
    vdom:  "root"
    state: "present"
    access_token: "{{ api_token }}"
    system_interface:
      vdom:  "root"
      name: "{{ new_vlan_name }}"
      mode: "static"
      allowaccess: "ping"
      interface: "DATACENTER"
      ip: "{{ new_vlan_gateway }}/{{ new_vlan_prefix }}"
      speed: "auto"
      status: "up"
      role: "lan"
      type: "vlan"
      vlan_protocol: "8021q"
      vlanid: "{{ new_vlan_id }}"

- name: Create new vlan object subnet
  fortios_firewall_address:
    vdom:  "root"
    state: "present"
    access_token: "{{ api_token }}"
    firewall_address:
      name: "{{ new_vlan_name }} address"
      type: "interface subnet"
      interface: "{{ new_vlan_name }}"
      subnet: "{{ new_vlan_subnet }}/ {{ new_vlan_prefix }}"
  
