--- 
- name: Configure SNMPv3
  ios_config:
    lines:
      - "snmp-server community {{ hostvars[inventory_hostname].community }} RO"
      - "snmp-server host {{nms_ip}} version 2c { hostvars[inventory_hostname].community }}"
  when: "hostvars[inventory_hostname].snmp == true"
