---
- name: Install SNMPD
  apt: pkg=snmpd state=present

- name: Download LibreNMS distro file from github to be able to determine OS with snmp 
  get_url:
    url: https://raw.githubusercontent.com/librenms/librenms-agent/master/snmp/distro
    dest: /usr/bin/distro
    mode: +x 

- name: Create /etc/snmp/snmpd.conf from template with community and location as variables
  template:                                                                     
    src: ./roles/snmp/files/snmpd.conf                            
    dest: /etc/snmp/
  notify: restart snmpd

- name: Download LibreNMS DHCP-SERVER file from github to be able to gather DHCP info with snmp 
  get_url:
    url: https://github.com/librenms/librenms-agent/raw/master/snmp/dhcp.py
    dest: /etc/snmp/dhcp.py
    mode: +x 
  notify: restart snmpd
  when: '"DHCP" in snmp.extend'

- name: Create /etc/snmp/dhcp.json file
  copy:                                                                     
    src: roles/snmp/files/dhcp.json                            
    dest: /etc/snmp/dhcp.json
  notify: restart snmpd
  when: '"DHCP" in snmp.extend'



  #- name: Check whether UFW is enabled
  #  shell: ufw status
  #  changed_when: False
  #  ignore_errors: True
  #  register: ufw_check
  #  become: true
  #
  #- name: Add SNMP rule to UFW for all pollers if UFW is enabled 
  #  ufw:
  #    rule: allow
  #    port: snmp 
  #    src: '10.10.110.8'
  #  when: "'active' in ufw_check.stdout"
  #  become: true
