---    
- name: Create port channels
  ios_config:
    lines:
      - "channel-group {{ item.lag.group }} mode {{ item.lag.mode}}"
    parents: "interface {{ item.name }}"
  with_items: "{{ interfaces }}"
  when: '"LAG" in item.config and item.lag.group is defined and item.lag.mode is defined'

- name: Create description on port channels
  ios_config:
    lines:
      - "description {{ item.description }}"
    parents: "interface {{ item.name }}"
  with_items: "{{ interfaces }}"
  when: 'item.type == "aggregated" and item.description is defined'

- name: Configure vlans on port channels
  ios_config:
    lines:
      - "switchport trunk encapsulation dot1q"
      - "switchport mode trunk"
      - "switchport trunk allowed vlan {{ item.tagged }}"
    parents: "interface {{ item.name }}"
  with_items:
    - "{{interfaces}}"
  when: '"ENCAPSULATION" in item.config and item.type == "aggregated"'

- name: No shutdown LAG interfaces
  ios_config:
    lines:
      - "no shutdown"
    parents: "interface {{ item.name }}"
  with_items: "{{ interfaces }}"
  when: '"LAG" in item.config and item.lag.group is defined and item.lag.mode is defined'
  changed_when: False

- name: No shutdown LAG interfaces
  ios_config:
    lines:
      - "no shutdown"
    parents: "interface {{ item.name }}"
  with_items: "{{ interfaces }}"
  when: 'item.type == "aggregated" and "LAG" in item.config'
  changed_when: False

